### ISSUE TITLE
Multi-node failure on parallelize_tasks_image3.rg

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#245]
Here is another multi-node failure. I believe this is a runtime bug because it only reproduces with `-finner 1` (not `-finner 0`) and Legion Spy reports an error. (Also, the test passes with bounds checks enabled, so I don't think the parallelized kernels themselves can be doing anything bad.)

```
./install.py --debug --gasnet
LAUNCHER='mpirun -n 2 -H localhost --bind-to none -x REALM_SYNTHETIC_CORE_MAP= -x INCLUDE_PATH -x LD_LIBRARY_PATH -x TERRA_PATH' ./regent.py ./tests/regent/run_pass/parallelize_tasks_image3.rg -ll:cpu 4 -fbounds-checks 1 -fparallelize-dop 4,4 -finner 1
```

Legion Spy reports:

```
ERROR: Missing source precondition for Realm Copy (220) on field f (101) for op region requirement 3 of stencil.parallelized on init.parallelized
```

Log files:

  * [spy_0.txt](https://github.com/StanfordLegion/legion/files/971457/spy_0.txt)
  * [spy_1.txt](https://github.com/StanfordLegion/legion/files/971459/spy_1.txt)

**Comment by elliottslaughter** [comment]
This appears to be related to whether you're using small or large instances for the regions.

If you go to DefaultMapper::default_policy_select_instance_region at default_mapper.cc:1996 and change the line `if (total_nodes == 1)` to `if (true)`, then the test passes even with `-finner 1`. Normally, `-finner 1` would cause Regent to avoid mapping a large instance of the data, whereas `-finner 0` would cause Regent to create an inline mapping up front. Thus the failure appears to be correlated with whether or not Regent is using small or big instances.

**Comment by elliottslaughter** [comment]
You can also use this to reproduce the failure on a single node.

Go to default_mapper.cc:1996 and change the condition to `if (false)`. This disables the special case for single node execution. Then run:

```
./regent.py ./tests/regent/run_pass/parallelize_tasks_image3.rg -ll:cpu 4 -fbounds-checks 1 -fparallelize-dop 4,4 -finner 1
```

**Comment by lightsighter** [comment]
Legion Spy validates the single node execution of this application.  Furthermore it runs correctly on the olddma branch.  Therefore I'm going to assign this bug to @jiazhihao to fix on a single node. Zhihao, once you get this fixed on a single node then assign the bug back to me and I will check the multi-node behavior.

**Comment by lightsighter** [comment]
The problem on a single node was not a DMA bug, but instead was a case where the runtime was allowing the mapper to choose an empty instance for a region that was not actually empty.  This problem is fixed with 818f4f9 and we should see no more problems on a single node.

However, I don't think this fixes the original multi-node bug that we saw of the missing precondition.  My guess is that this bug still exists.  However, I also think that this issue is the same as #246.  Assigning back to myself for now.

**Comment by elliottslaughter** [comment]
I think you did actually fix the multi-node bug. The original bug reproduced 100% for me, and after the change I can't repro after 200 runs. Gitlab also doesn't repro anymore, and it was again reproing 100% before the change.

Meanwhile, #246 is still reproing just fine. I think these are actually different bugs.

I'll leave this open for the moment, but I think this bug is fixed.

**Comment by lightsighter** [comment]
Definitely not fixed.  The error message in the logs above has nothing to do with the thing that I fixed for single node.  Here is an experiment, try running the multi-node version, but run Legion Spy on the log files regardless of whether the run passes or fails.  I bet it fails every single time (#246 definitely does).

**Comment by elliottslaughter** [comment]
Yeah, it is still there:

```
ERROR: Missing source precondition for Realm Copy (106) on field f (101) for op region requirement 0 of stencil_serial on init.parallelized
```

I suppose we should be running multi-node spy tests....

**Comment by lightsighter** [comment]
This should be fixed with 85083a4.  Assigning back to @elliottslaughter to confirm.

**Comment by elliottslaughter** [comment]
Confirmed.
